### ISSUE TITLE
Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Chef has folder structure and requires a reboot", :timestamp=>2017-06-20 17:20:19 +0100, :requested_by=>"temp_folder_requires_reboot"}

### ISSUE THREAD

**Issue by tolland** [chrisgit/test_kitchen-multiboot#1]
If I run this cookbook with a Windows 2008 R2 guest, it gets to the point where it reboots;
`       [2017-06-20T17:20:19+01:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Chef has folder structure and requires a reboot", :timestamp=>2017-06-20 17:20:19 +0100, :requested_by=>"temp_folder_requires_reboot"}`

but immediately follows up with a FATAL error;
```
 [2017-06-20T17:20:19+01:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-06-20T17:20:19+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-06-20T17:20:19+01:00] FATAL: Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Chef has folder structure and requires a reboot", :timestamp=>2017-06-20 17:20:19 +0100, :requested_by=>"temp_folder_requires_reboot"}
```

The stacktrace.out file contains this;
```
Generated at 2017-06-20 17:20:19 +0100
Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Chef has folder structure and requires a reboot", :timestamp=>2017-06-20 17:20:19 +0100, :requested_by=>"temp_folder_requires_reboot"}
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/platform/rebooter.rb:54:in `reboot!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/platform/rebooter.rb:61:in `reboot_if_needed!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/client.rb:306:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'
```

**Comment by tolland** [comment]
[output.txt](https://github.com/chrisgit/test_kitchen-multiboot/files/1088923/output.txt)
So the "kitchen converge" command returns with the following message;
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [execution expired] on default-W2008-15-05
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Any idea what I am doing wrong?

**Comment by chrisgit** [comment]
Hello @tolland 

Thank you for logging this issue.

I've modified the kitchen.yml to use the Opentable Win2008r2 image

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero 
  require_chef_omnibus: latest
  retry_on_exit_code:
    - 35
    - 20
    - 1
  wait_for_retry: 60
  max_retries: 10
  client_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec

platforms:
- name: windows2008r2
  driver:
    box: opentable/win-2008r2-standard-amd64-nocm
    gui: true

suites:
- name: default
  run_list: 
    - "recipe[multiboot]"
  verifier:
    inspec_tests:
      - test/smoke/default  
  attributes: { "default_attributes": {} }
```

Crashes for me too, so I've tried some of the suggestions from

https://github.com/test-kitchen/test-kitchen/issues/1218
https://github.com/test-kitchen/test-kitchen/issues/1062
https://github.com/chef/chef/issues/5026
https://github.com/test-kitchen/test-kitchen/issues/1227

I suspect it is an issue with Test Kitchen rather than the example program.
